### ISSUE TITLE
feat: 1대1 문의에서 사용할 구매내역 리스트 조회 기능 구현

### ISSUE THREAD

**Issue by JeYeongR** [KDT3-Final-6/final-project-BE#177]
## Description

1대1 문의에서 사용할 구매내역 리스트 조회 기능 구현
기존 구매내역보다 간단하게 해서 보낼려고 합니다.

## Tasks(Process)

- [x] 1대1 문의에서 사용할 구매내역 리스트 조회 기능 구현

**Comment by zoomin3022** [comment]
확인했습니다
